export const QUERY = 'TM_getallinfo_controller'//查询接口
export const ADD = 'TM_insertone_controller'//添加接口
export const UPDATE = 'TM_updateone_controller'//更新接口
export const DELETE = 'TM_deletebatchbydeletekeys_controller'//删除接口
export const LOGIN = 'TM_ocp_UserLogin' //登录接口
export const UPLOADIMG = 'SevenCattleCloudPictureUpload'//上次图片接口
export const USERINFO = 'TM_ocp_atoTokengetUserInfo'//根据token拿到用户信息
export const EXAMINFO = 'TM_ocp_atopaperidgetrandomInfo'//根据试题类型与试卷类型 获取随即试卷信息
export const RECORDINFO = 'TM_ocp_setUpStudyrecordInfo'//模拟支付成功回调生成课程信息以及章节信息
export const STUDYRECORD = 'TM_ocp_replaceStudyrecord' //生成课程学习记录